title: 7.12 Acre Property in Ringgold
description: Cleared and ready-to-build homesite for sale by owner in Ringgold, GA.
baseurl: "" # Leave blank if hosting at root, like GitHub Pages user site
url: "https://158bowman.com" # Replace with your domain or GitHub Pages URL
theme: null
markdown: kramdown
exclude: ["README.md", "Gemfile", "Gemfile.lock", "node_modules"]
